# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Topbar = QtWidgets.QFrame(self.centralwidget)
        self.Topbar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Topbar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Topbar.setObjectName("Topbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Topbar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_top = QtWidgets.QFrame(self.Topbar)
        self.frame_top.setMaximumSize(QtCore.QSize(100, 40))
        self.frame_top.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_toggle = QtWidgets.QPushButton(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_toggle.sizePolicy().hasHeightForWidth())
        self.Btn_toggle.setSizePolicy(sizePolicy)
        self.Btn_toggle.setStyleSheet("color:rgb(255, 255, 255);\n"
"border: 0px solid")
        self.Btn_toggle.setObjectName("Btn_toggle")
        self.horizontalLayout_2.addWidget(self.Btn_toggle)
        self.horizontalLayout.addWidget(self.frame_top)
        self.frame_toggle = QtWidgets.QFrame(self.Topbar)
        self.frame_toggle.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_toggle.setStyleSheet("background-color: rgb(57, 57, 57);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.Btn_import = QtWidgets.QPushButton(self.frame_toggle)
        self.Btn_import.setGeometry(QtCore.QRect(10, 5, 89, 25))
        self.Btn_import.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    color : #FFF;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.Btn_import.setObjectName("Btn_import")
        self.label_file_path = QtWidgets.QLabel(self.frame_toggle)
        self.label_file_path.setGeometry(QtCore.QRect(110, 5, 391, 25))
        self.label_file_path.setStyleSheet("background-color: #FFF;\n"
"color :rgb(150, 150, 150)")
        self.label_file_path.setObjectName("label_file_path")
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.verticalLayout.addWidget(self.Topbar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(57, 57, 57);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Btn_linear = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_linear.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_linear.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_linear.setObjectName("Btn_linear")
        self.verticalLayout_4.addWidget(self.Btn_linear)
        self.Btn_poly_reg = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_poly_reg.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_poly_reg.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_poly_reg.setObjectName("Btn_poly_reg")
        self.verticalLayout_4.addWidget(self.Btn_poly_reg)
        self.Btn_kmeans = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_kmeans.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_kmeans.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_kmeans.setObjectName("Btn_kmeans")
        self.verticalLayout_4.addWidget(self.Btn_kmeans)
        self.Btn_ML = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_ML.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_ML.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_ML.setObjectName("Btn_ML")
        self.verticalLayout_4.addWidget(self.Btn_ML)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Pages_widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_widget.setObjectName("Pages_widget")
        self.Learning = QtWidgets.QWidget()
        self.Learning.setObjectName("Learning")
        self.label_learning = QtWidgets.QLabel(self.Learning)
        self.label_learning.setGeometry(QtCore.QRect(0, 0, 210, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_learning.setFont(font)
        self.label_learning.setStyleSheet("color: #FFF;")
        self.label_learning.setAlignment(QtCore.Qt.AlignCenter)
        self.label_learning.setObjectName("label_learning")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Learning)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 70, 861, 161))
        self.textBrowser_2.setStyleSheet("color: #FFF")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Pages_widget.addWidget(self.Learning)
        self.kmeans_cluster = QtWidgets.QWidget()
        self.kmeans_cluster.setObjectName("kmeans_cluster")
        self.label_kmeans = QtWidgets.QLabel(self.kmeans_cluster)
        self.label_kmeans.setGeometry(QtCore.QRect(0, 0, 195, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_kmeans.setFont(font)
        self.label_kmeans.setStyleSheet("color: #FFF;")
        self.label_kmeans.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kmeans.setObjectName("label_kmeans")
        self.Btn_elbow_plot = QtWidgets.QPushButton(self.kmeans_cluster)
        self.Btn_elbow_plot.setGeometry(QtCore.QRect(0, 280, 111, 40))
        self.Btn_elbow_plot.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_elbow_plot.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_elbow_plot.setObjectName("Btn_elbow_plot")
        self.textBrowser = QtWidgets.QTextBrowser(self.kmeans_cluster)
        self.textBrowser.setGeometry(QtCore.QRect(0, 70, 861, 161))
        self.textBrowser.setStyleSheet("color: #FFF")
        self.textBrowser.setObjectName("textBrowser")
        self.Btn_cluster_kmeans = QtWidgets.QPushButton(self.kmeans_cluster)
        self.Btn_cluster_kmeans.setGeometry(QtCore.QRect(0, 330, 211, 40))
        self.Btn_cluster_kmeans.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_cluster_kmeans.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_cluster_kmeans.setObjectName("Btn_cluster_kmeans")
        self.cluster_max = QtWidgets.QSpinBox(self.kmeans_cluster)
        self.cluster_max.setGeometry(QtCore.QRect(120, 290, 48, 26))
        self.cluster_max.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cluster_max.setMinimum(1)
        self.cluster_max.setMaximum(20)
        self.cluster_max.setObjectName("cluster_max")
        self.label_clustermax = QtWidgets.QLabel(self.kmeans_cluster)
        self.label_clustermax.setGeometry(QtCore.QRect(190, 295, 401, 17))
        self.label_clustermax.setStyleSheet("color: #FFF")
        self.label_clustermax.setObjectName("label_clustermax")
        self.cluster_number = QtWidgets.QSpinBox(self.kmeans_cluster)
        self.cluster_number.setGeometry(QtCore.QRect(220, 340, 48, 26))
        self.cluster_number.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cluster_number.setMinimum(1)
        self.cluster_number.setMaximum(20)
        self.cluster_number.setObjectName("cluster_number")
        self.label_cluster = QtWidgets.QLabel(self.kmeans_cluster)
        self.label_cluster.setGeometry(QtCore.QRect(290, 345, 401, 17))
        self.label_cluster.setStyleSheet("color: #FFF")
        self.label_cluster.setObjectName("label_cluster")
        self.Pages_widget.addWidget(self.kmeans_cluster)
        self.Linear_reg = QtWidgets.QWidget()
        self.Linear_reg.setObjectName("Linear_reg")
        self.label_linear = QtWidgets.QLabel(self.Linear_reg)
        self.label_linear.setGeometry(QtCore.QRect(0, 0, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_linear.setFont(font)
        self.label_linear.setStyleSheet("color: #FFF;")
        self.label_linear.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linear.setObjectName("label_linear")
        self.plot_linearreg = QtWidgets.QPushButton(self.Linear_reg)
        self.plot_linearreg.setGeometry(QtCore.QRect(0, 90, 120, 40))
        self.plot_linearreg.setMinimumSize(QtCore.QSize(0, 40))
        self.plot_linearreg.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.plot_linearreg.setObjectName("plot_linearreg")
        self.label_axis = QtWidgets.QLabel(self.Linear_reg)
        self.label_axis.setGeometry(QtCore.QRect(140, 90, 51, 41))
        self.label_axis.setStyleSheet("color: #FFF")
        self.label_axis.setObjectName("label_axis")
        self.x_axis_linear = QtWidgets.QSpinBox(self.Linear_reg)
        self.x_axis_linear.setGeometry(QtCore.QRect(210, 100, 48, 26))
        self.x_axis_linear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_axis_linear.setMinimum(0)
        self.x_axis_linear.setMaximum(10)
        self.x_axis_linear.setObjectName("x_axis_linear")
        self.label_ord = QtWidgets.QLabel(self.Linear_reg)
        self.label_ord.setGeometry(QtCore.QRect(280, 90, 51, 41))
        self.label_ord.setStyleSheet("color: #FFF")
        self.label_ord.setObjectName("label_ord")
        self.y_ord_linear = QtWidgets.QSpinBox(self.Linear_reg)
        self.y_ord_linear.setGeometry(QtCore.QRect(350, 100, 48, 26))
        self.y_ord_linear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.y_ord_linear.setMinimum(0)
        self.y_ord_linear.setMaximum(10)
        self.y_ord_linear.setObjectName("y_ord_linear")
        self.Pages_widget.addWidget(self.Linear_reg)
        self.polynomial_reg = QtWidgets.QWidget()
        self.polynomial_reg.setObjectName("polynomial_reg")
        self.label_polynomial_reg = QtWidgets.QLabel(self.polynomial_reg)
        self.label_polynomial_reg.setGeometry(QtCore.QRect(0, 0, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_polynomial_reg.setFont(font)
        self.label_polynomial_reg.setStyleSheet("color: #FFF;")
        self.label_polynomial_reg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_polynomial_reg.setObjectName("label_polynomial_reg")
        self.plot_polynomial = QtWidgets.QPushButton(self.polynomial_reg)
        self.plot_polynomial.setGeometry(QtCore.QRect(0, 90, 120, 40))
        self.plot_polynomial.setMinimumSize(QtCore.QSize(0, 40))
        self.plot_polynomial.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.plot_polynomial.setObjectName("plot_polynomial")
        self.label_degree = QtWidgets.QLabel(self.polynomial_reg)
        self.label_degree.setGeometry(QtCore.QRect(140, 90, 111, 41))
        self.label_degree.setStyleSheet("color: #FFF")
        self.label_degree.setObjectName("label_degree")
        self.degree_polynomial = QtWidgets.QSpinBox(self.polynomial_reg)
        self.degree_polynomial.setGeometry(QtCore.QRect(270, 100, 48, 26))
        self.degree_polynomial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.degree_polynomial.setMinimum(1)
        self.degree_polynomial.setMaximum(6)
        self.degree_polynomial.setObjectName("degree_polynomial")
        self.label_ord_poly = QtWidgets.QLabel(self.polynomial_reg)
        self.label_ord_poly.setGeometry(QtCore.QRect(280, 140, 51, 41))
        self.label_ord_poly.setStyleSheet("color: #FFF")
        self.label_ord_poly.setObjectName("label_ord_poly")
        self.y_ord_linear_poly = QtWidgets.QSpinBox(self.polynomial_reg)
        self.y_ord_linear_poly.setGeometry(QtCore.QRect(350, 150, 48, 26))
        self.y_ord_linear_poly.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.y_ord_linear_poly.setMinimum(0)
        self.y_ord_linear_poly.setMaximum(10)
        self.y_ord_linear_poly.setObjectName("y_ord_linear_poly")
        self.label_axis_poly = QtWidgets.QLabel(self.polynomial_reg)
        self.label_axis_poly.setGeometry(QtCore.QRect(140, 140, 51, 41))
        self.label_axis_poly.setStyleSheet("color: #FFF")
        self.label_axis_poly.setObjectName("label_axis_poly")
        self.x_axis_linear_poly = QtWidgets.QSpinBox(self.polynomial_reg)
        self.x_axis_linear_poly.setGeometry(QtCore.QRect(210, 150, 48, 26))
        self.x_axis_linear_poly.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_axis_linear_poly.setMinimum(0)
        self.x_axis_linear_poly.setMaximum(10)
        self.x_axis_linear_poly.setObjectName("x_axis_linear_poly")
        self.Pages_widget.addWidget(self.polynomial_reg)
        self.verticalLayout_2.addWidget(self.Pages_widget)
        self.horizontalLayout_3.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_toggle.setText(_translate("MainWindow", "ML APP"))
        self.Btn_import.setText(_translate("MainWindow", "Import file"))
        self.label_file_path.setText(_translate("MainWindow", "File path"))
        self.Btn_linear.setText(_translate("MainWindow", "Linear\n"
"regression"))
        self.Btn_poly_reg.setText(_translate("MainWindow", "Polynomial\n"
"regression"))
        self.Btn_kmeans.setText(_translate("MainWindow", "Clustering"))
        self.Btn_ML.setText(_translate("MainWindow", "Learning"))
        self.label_learning.setText(_translate("MainWindow", "Learning"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is the Machine Learning platfom. Its purpose is to make the process of applying machine learning algorithms easier.</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please start by importing a CSV or TXT file using the import button. Note that for the moment, the algorithms are only supporting numeric datasets, with eventually one classification column.</p></body></html>"))
        self.label_kmeans.setText(_translate("MainWindow", "Clustering"))
        self.Btn_elbow_plot.setText(_translate("MainWindow", "Elbow method"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">WARNING : To experience a correct usage of the cluster method, please get your dataset to encounter these requirements :</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- is a csv file</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- the collumn used for classification has less than 6 different classes AND is the las column in the dataset</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- the other collumns comport numerical values</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To correctly choose the cluster number, use the elbow method and pick the cluster value corresponding to the elbow of the curve.</p></body></html>"))
        self.Btn_cluster_kmeans.setText(_translate("MainWindow", "Clustering with Kmeans"))
        self.label_clustermax.setText(_translate("MainWindow", "Maximum number of clusters for the elbow method"))
        self.label_cluster.setText(_translate("MainWindow", "Number of clusters for Kmeans"))
        self.label_linear.setText(_translate("MainWindow", "Linear Regression"))
        self.plot_linearreg.setText(_translate("MainWindow", "Plot linear \n"
"regression"))
        self.label_axis.setText(_translate("MainWindow", "X axis"))
        self.label_ord.setText(_translate("MainWindow", "Y axis"))
        self.label_polynomial_reg.setText(_translate("MainWindow", "Polynomial regression"))
        self.plot_polynomial.setText(_translate("MainWindow", "Plot polynomial \n"
"regression"))
        self.label_degree.setText(_translate("MainWindow", "Select a degree"))
        self.label_ord_poly.setText(_translate("MainWindow", "Y axis"))
        self.label_axis_poly.setText(_translate("MainWindow", "X axis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
